version: "3"
services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/mysqldata:/var/lib/mysql
  redis:
    image: redis:7
    restart: always
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ${PWD}/redisdata/data:/data
    ports:
      - 6379:6379
  worker:
    image: ghcr.io/neilkuan/example-go-http:v0.2.0-worker
    restart: always
    container_name: worker
    environment:
      - REDIS_HOST=redis:6379
    volumes:
      - ${PWD}/redisdata/data:/data
    ports:
      - 8080:8080