# syntax=docker/dockerfile:1

FROM --platform=linux/amd64 golang:1.21 AS build-stage

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /frontend

# Deploy the application binary into a lean image
FROM --platform=linux/amd64 gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /frontend /frontend

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/frontend"]